#!/usr/bin/env ruby
require 'pathname'
require 'fileutils'

# TODO: cd pwd func wrapper
# TODO: sshh module @home, shell, github().pull/clone

# Paths and utils
module Base
  def home
    Pathname.new('~').expand_path
  end

  def newhome
    p(home) unless home.exist?
  end

  def p(base, *subs)
    dir = Pathname.new(base).join(*subs).expand_path
    FileUtils.mkdir_p(dir) unless dir.exist?
    dir
  end

  module_function :home, :newhome, :p

  def github(repo)
    local = Pathname.new(repo.split('/').last)
    if local.exist? && (local / '.git').exist?
      system("git -C #{local.realpath} pull")
    else
      system("git clone https://github.com/#{repo}")
    end
  end
end

# Vim plugins
class Vim
  extend Base
  @pkgs = %w[

    hrls/bullfinch
    vim-airline/vim-airline

    junegunn/fzf.vim
    majutsushi/tagbar
    scrooloose/nerdtree
    vim-scripts/restore_view.vim

    rust-lang/rust.vim
    racer-rust/vim-racer
    tpope/vim-markdown
    chr4/nginx.vim
  ]

  def self.packages
    autoload_dir = p(home / '.vim' / 'autoload')
    pathogen = autoload_dir / 'pathogen.vim'
    system("curl -LSso #{pathogen} https://tpo.pe/pathogen.vim")

    bundles = p(home / '.vim' / 'bundle')
    FileUtils.cd(bundles, verbose: true)
    @pkgs.each { |pkg| github pkg }
  end
end

# Env / shell / etc
class Env
  extend Base

  @dotfiles = %w[
    .gitconfig
    .gitignore
    .vimrc
    .zshenv
    .hidden

    .ghci
    .tmux.conf
    .psqlrc
  ]

  def self.linkdots
    pre = Pathname.pwd.relative_path_from(home)
    @dotfiles.each do |dotfile|
      FileUtils.ln_s(pre / dotfile, home, force: true, verbose: true)
    end
  end

  def self.hushlogin
    hl = home / '.hushlogin'
    system("touch #{hl}") unless hl.exist?
  end

  def self.dotlocal
    p(home / '.local' / 'bin')
    p(home / '.local' / 'var')
  end
end

# TODO: symlinks scripts/* ~/.local/bin

Base.newhome

Env.hushlogin
Env.dotlocal
Env.linkdots

Vim.packages
