#!/usr/bin/env zsh

if [[ $# != 1 ]]; then
echo "usage: uninstall-with-deps <brew formula>"
return -1
fi

formula=$1
brew rm ${formula}
if [[ $? != 0 ]]; then return -2; fi

dangled_deps=$(join <(brew leaves) <(brew deps ${formula}))

if [[ ${dangled_deps} != '' ]]; then
brew rm ${dangled_deps}
fi
