#!/usr/bin/env ruby
require 'pathname'
require 'fileutils'

content_to = Pathname.new('/Volumes/rttr')
content_to = content_to.join(*ARGV) unless ARGV.is_empty?

torrents = Pathname.new('~').expand_path.join('Downloads', '*.torrent')
torrents = Pathname.glob(torrents)

case torrents.size
when 0
  puts 'no any torrent file in Downloads folder'
when 1
  torrent_file = torrents.first.realpath
  if $DEBUG
    puts torrent_file
    puts content_to
  end
  retval = system("btcli add '#{torrent_file}' -d '#{content_to}'")
  FileUtils.rm(torrent_file) if retval
else
  puts 'todo: show prompt'
end
